# Generated by Django 2.2.4 on 2020-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201031_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Pastry', 'Pastry'), ('Toasts', 'Toasts'), ('Chicken Meals', 'Chicken Meals'), ('Burgers', 'Burgers'), ('Meat Meals', 'Meat Meals'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Pastas', 'Pastas'), ('Salads', 'Salads'), ('Desserts', 'Desserts'), ('Cold Drinks', 'Cold Drinks'), ('Hot Drinks', 'Hot Drinks'), ('Side Dishes', 'Side Dishes')], max_length=200),
        ),
    ]
