# Generated by Django 2.2.4 on 2020-10-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_restaurant_average_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='average_score',
        ),
    ]
