# Generated by Django 2.2.4 on 2020-11-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201031_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount_History',
        ),
    ]
